/**
 * Copyright 2014-2016 Steven T Sell (ssell@vertexfragment.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once
#ifndef __H__OCULAR_CORE_LIGHT_MANAGER__H__
#define __H__OCULAR_CORE_LIGHT_MANAGER__H__

#include "Scene/Light/LightSource.hpp"
#include "Scene/Light/GPULight.hpp"
#include "Math/Geometry/Frustum.hpp"

#include <vector>
#include <unordered_map>

//------------------------------------------------------------------------------------------

/**
 * \addtogroup Ocular
 * @{
 */
namespace Ocular
{
    namespace Graphics
    {
        class GPUBuffer;
    }

    /**
     * \addtogroup Core
     * @{
     */
    namespace Core
    {
        /**
         * \class LightManager
         *
         * Handles updating the GPU light buffer with current scene's lighting.
         * All light sources are uploaded as instances of the GPULight structures.
         *
         * Ambient lighting is always passed over in the buffers 0 index, with the
         * number of lights recorded in it's light type property (Buffer[0].parameters.z).
         *
         * Culling of visible lights is done using simple frustum culling against 
         * bounding volumes generated by the light's properties (bounding spheres
         * for point lights).
         * 
         * Directional and ambient lights are not culled as they affect the entire
         * scene by their very definition.
         *
         * In Direct3D, the light structured buffer is passed over register t8.
         * See LightManager::LightBufferSlot
         */
        class LightManager
        {
            friend class LightSource;

        public:

            LightManager();
            ~LightManager();

            /**
             * Updates the GPU light buffer. 
             * 
             * For Direct3D, this buffer is passed over register t8.
             *
             * \param[in] cullVisible If TRUE, only visible lights will be passed to the GPU.
             */
            void updateLights(bool cullVisible = true);

            /**
             * Sets the ambient light color. 
             * \param[in] color
             */
            void setAmbientLightColor(Color const& color);

            /**
             * \return The current ambient light color.
             */
            Color getAmbientLightColor() const;

            /**
             * Sets the ambient light intensity. Intensity is clamped to [0,1].
             * \param[in] intensity
             */
            void setAmbientLightIntensity(float intensity);

            /**
             * \return The currently ambient light intensity.
             */
            float getAmbientLightIntensity() const;

            static const uint32_t LightBufferSlot;    ///< The GPUBuffer slot used by the LightManager to pass light data

        protected:

            void registerLightSource(LightSource* light);
            void unregisterLightSource(LightSource* light);
            void updateUUID(UUID const& uuid);

            void getVisibleLights(std::vector<LightSource*>& visibleLights, bool cull);
            bool isLightVisible(LightSource const* light, Math::Frustum const& frustum) const;
            bool isPointLightVisible(LightSource const* light, Math::Frustum const& frustum) const;
            bool isSpotlightVisible(LightSource const* light, Math::Frustum const& frustum) const;
            bool isDirectionalLightVisible(LightSource const* light, Math::Frustum const& frustum) const;

            void buildGPUBuffer(uint32_t visibleCount);
            void fillGPUBuffer(std::vector<LightSource*> const& visibleLights);

            //------------------------------------------------------------

            std::unordered_map<std::string, LightSource*> m_Lights;   // Key is UUID string
            std::vector<GPULight> m_GPULights;

            Graphics::GPUBuffer* m_GPUBuffer;  // Buffer to store light data for GPU use
            uint32_t m_BufferLightCapacity;    // Maximum number of lights the current GPU buffer can store
            uint32_t m_PrevNumVisible;         // Number of visible lights at last update (used to determine if we need to clear GPU buffer)

            GPULight m_GPUAmbientLight;

        private:
        };
    }
    /**
     * @} End of Doxygen Groups
     */
}
/**
 * @} End of Doxygen Groups
 */

//------------------------------------------------------------------------------------------

#endif 